name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          pnpm-version: 8.5.1
          node-version: 16.x
          args: "--frozen-lockfile"
      - name: Lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          pnpm-version: 8.5.1
          node-version: 16.x
          no-lockfile: true
      - name: Run tests
        run: pnpm test

  try-scenarios:
    name: "ember-try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    needs: "test"

    strategy:
      fail-fast: false
      matrix:
        ember-try-scenario:
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          pnpm-version: 8.5.1
          node-version: 16.x
          args: "--frozen-lockfile"
      - name: Run tests
        run: pnpm ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
        working-directory: test-app
