name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.5.1
          node-version: 18.x
          args: "--frozen-lockfile"
      - name: Lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.5.1
          node-version: 18.x
          args: "--no-lockfile"
      - name: Run tests
        run: pnpm test

  try-scenarios:
    name: "ember-try: ${{ matrix.ember-try-scenario }}"
    runs-on: ubuntu-latest
    needs: "test"

    strategy:
      fail-fast: false
      matrix:
        ember-try-scenario:
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-lts-4.8
          - ember-lts-4.12
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.5.1
          node-version: 18.x
          args: "--frozen-lockfile"
      - name: Run tests
        run: pnpm ember try:one ${{ matrix.ember-try-scenario }} --skip-cleanup
        working-directory: test-app

  typescript-compatibility:
    name: Type checking - ${{ matrix.typescript-scenario }}
    runs-on: ubuntu-latest

    needs: [test]

    strategy:
      fail-fast: false
      matrix:
        typescript-scenario:
          - typescript@5.0
          - typescript@5.1
          - typescript@next

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: wyvox/action-setup-pnpm@v3
        with:
          pnpm-version: 8.5.1
          node-version: 18.x
          args: "--frozen-lockfile"
      - name: Update TS version on addon package
        run: pnpm add -D ${{ matrix.typescript-scenario }}
        working-directory: ember-autofocus-modifier
      - name: Update TS version on test-app package
        run: pnpm add -D ${{ matrix.typescript-scenario }}
        working-directory: test-app
      - name: Type checking
        run: pnpm lint:types
